### ISSUE TITLE
Single Type with a hyphen breaks plugin configuration

### ISSUE THREAD

**Issue by kasonde** [strapi/gatsby-source-strapi#219]
### Describe the bug

When I try to configure the plugin with a singleType "home-page" in my Strapi backend, the plugin is unable to build the schema and the gatsby dev-server is unable to start.

### Steps to reproduce the behavior

1. Install the plugin
2. Configure in a manner similar to the snippet below
3. Make sure you have a single type with a hyphen `-` in it
4. Run gatsby and see the error

### Stack Trace

```
Missing onError handler for invocation 'building-schema', error was 'Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "StrapiHome-page" does not.'. Stacktrace was 'GraphQLError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but
"StrapiHome-page" does not.
    at isValidNameError (/directory/strapi-front-end/node_modules/graphql/utilities/assertValidName.js:42:12)
    at assertValidName (/directory/strapi-front-end/node_modules/graphql/utilities/assertValidName.js:21:15)
    at checkIsAllowedTypeName (/directory/strapi-front-end/node_modules/gatsby/src/schema/schema.js:608:3)
    at forEach (/directory/strapi-front-end/node_modules/gatsby/src/schema/schema.js:313:9)
    at Array.forEach (<anonymous>)
    at addTypes (/directory/strapi-front-end/node_modules/gatsby/src/schema/schema.js:275:9)
    at updateSchemaComposer (/directory/strapi-front-end/node_modules/gatsby/src/schema/schema.js:162:9)
    at buildSchema (/directory/strapi-front-end/node_modules/gatsby/src/schema/schema.js:64:9)
    at build (/directory/strapi-front-end/node_modules/gatsby/src/schema/index.js:105:24)
    at buildSchema (/directory/strapi-front-end/node_modules/gatsby/src/services/build-schema.ts:19:3)'

⠴ building schema
```

### Code snippets 
My `gatsby-config.js`
```
module.exports = {
  siteMetadata: {
    title: "Strapi Front-end",
  },
  plugins: [
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-sitemap",
    {
      resolve: "gatsby-source-strapi",
      options: {
        apiURL: "http://localhost:1337",
        collectionTypes: ["dogs", "pages"],
        singleTypes: ["home-page"],
      },
    },
    {
      resolve: "gatsby-plugin-manifest",
      options: {
        icon: "src/images/icon.png",
      },
    },
  ],
}

```

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Operating system: Pop! OS 20.10

**Comment by kasonde** [comment]
Closing this since it seems that after some reading, this is a GraphQL spec rule to not have hyphens in [naming schemes](https://spec.graphql.org/June2018/#sec-Names).
